
IF   EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[CreateTables]') AND type IN ('P'))
     DROP PROCEDURE[dbo].[CreateTables]
GO

CREATE PROCEDURE[dbo].[CreateTables]
AS
BEGIN

   IF NOT EXISTS(SELECT* FROM sys.tables WHERE name='JOBS')
   BEGIN
     CREATE TABLE JOBS(
	  JOB_ID INT PRIMARY KEY,
	  JOB_TITLE VARCHAR(100) NOT NULL,
	  MIN_SALARY DECIMAL(10,2),
	  MAX_SALARY DECIMAL(10,2)
	 )
	 END

	 IF NOT EXISTS(SELECT* FROM sys.tables WHERE name='REGIONS')
	 BEGIN
	   CREATE TABLE REGIONS(
	    REGION_ID INT PRIMARY KEY,
	    REGION_NAME VARCHAR(100) NOT NULL
	   )
	END

	IF NOT EXISTS(SELECT* FROM sys.tables WHERE name= 'COUNTRIES')
	BEGIN
	   CREATE TABLE COUNTRIES(
	     COUNTRY_ID INT PRIMARY KEY,
		 COUNTRY_NAME VARCHAR(100) NOT NULL,
		 REGION_ID INT
		 FOREIGN KEY(REGION_ID) REFERENCES REGIONS(REGION_ID)
		 )
	END

 IF NOT EXISTS(SELECT* FROM sys.tables WHERE name='LOCATIONS')
 BEGIN
  CREATE TABLE LOCATIONS(
   LOCATION_ID INT PRIMARY KEY,
   STREET_ADDRESS VARCHAR(100),
   POSTAL_CODE VARCHAR(20),
   CITY VARCHAR(100),
   STATE_PROVINCE VARCHAR(100),
   COUNTRY_ID INT
   FOREIGN KEY(COUNTRY_ID) REFERENCES CONTRIES(COUNTRY_ID)
   )
   END

    IF NOT EXISTS(SELECT* FROM sys.tables WHERE name='DEPARTMENTS')
  BEGIN
     CREATE TABLE DEPARTMENTS(
	  DEPARTMENT_ID INT PRIMARY KEY,
	  DEPARTMENT_NAME VARCHAR(100) NOT NULL,
	  MANAGER_ID INT,
	  LOCATION_ID INT
	  FOREIGN KEY(LOCATION_ID) REFERENCES LOCATIONS(LOCATION_ID)
   )
   END

   IF NOT EXISTS(SELECT* FROM sys.tables WHERE name = 'EMPLOYEES')
   BEGIN
    CREATE TABLE EMPLOYEES(
	 EMPLOYEE_ID INT PRIMARY KEY,
	 FIRST_NAME VARCHAR(50) NOT NULL,
	 LAST_NAME VARCHAR(50) NOT NULL,
	 EMAIL VARCHAR(100) UNIQUE NOT NULL,
	 PHONE_NUMBER VARCHAR(10),
	 HIRE_DATE DATE NOT NULL,
	 JOB_ID INT NOT NULL,
	 SALARY DECIMAL(10,2) NOT NULL,
	 COMISSION_PCT DECIMAL(10,2),
	 MANAGER_ID INT,
	 DEPARTMENT_ID INT,
	 FOREIGN KEY(DEPARTMENT_ID) REFERENCES DEPARTMENTS(DEPARTMENT_ID),
	 FOREIGN KEY(EMPLOYEE_ID) REFERENCES EMPLOYEES(EMPLOYEE_ID),
	 FOREIGN KEY(JOB_ID) REFERENCES JOBS(JOB_ID)
	 )
	 END

	 IF NOT EXISTS(SELECT* FROM sys.tables WHERE name='JOB_HISTORY')
	 BEGIN
	    CREATE TABLE JOB_HISTORY(
		 EMPLOYEE_ID INT,
		 STARTING_DATE DATE,
		 END_DATE DATE,
		 JOB_ID INT,
		 DEPARTMENT_ID INT,
		 PRIMARY KEY(EMPLOYEE_ID,STARTING_DATE),
		 FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEES(EMPLOYEE_ID),
		 FOREIGN KEY (DEPARTMENT_ID) REFERENCES DEPARTMENTS(DEPARTMENT_ID),
		 FOREIGN KEY (JOB_ID) REFERENCES JOBS(JOB_ID)
		 )
		 END
		END

		GO
		EXEC [dbo].[CreateTables]



IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[InsertData]') AND type IN ('P'))
    DROP PROCEDURE [dbo].[InsertData]
GO

CREATE PROCEDURE [dbo].[InsertData]
AS
BEGIN
    IF NOT EXISTS (SELECT * FROM REGIONS WHERE REGION_ID = 1)
        INSERT INTO REGIONS VALUES (1, 'Burgas');
    
    IF NOT EXISTS (SELECT * FROM REGIONS WHERE REGION_ID = 2)
        INSERT INTO REGIONS VALUES (2, 'Berlin');

    IF NOT EXISTS (SELECT * FROM COUNTRIES WHERE COUNTRY_ID = 1)
        INSERT INTO COUNTRIES VALUES (1, 'Bulgaria', 1);
    
    IF NOT EXISTS (SELECT * FROM COUNTRIES WHERE COUNTRY_ID = 2)
        INSERT INTO COUNTRIES VALUES (2, 'Germany', 2);

    IF NOT EXISTS (SELECT * FROM LOCATIONS WHERE LOCATION_ID = 1)
        INSERT INTO LOCATIONS VALUES (1, 'OBORISHTE', '8000', 'Burgas', 'Burgas', 1);
    
    IF NOT EXISTS (SELECT * FROM LOCATIONS WHERE LOCATION_ID = 2)
        INSERT INTO LOCATIONS VALUES (2, 'SHWARTS-STRASSE', '1500', 'Berlin', 'Berlin', 2);

    IF NOT EXISTS (SELECT * FROM DEPARTMENTS WHERE DEPARTMENT_ID = 10)
        INSERT INTO DEPARTMENTS VALUES (10, 'Marketing', 101, 1);
    
    IF NOT EXISTS (SELECT * FROM DEPARTMENTS WHERE DEPARTMENT_ID = 11)
        INSERT INTO DEPARTMENTS VALUES (11, 'IT', 117, 2);

    IF NOT EXISTS (SELECT * FROM JOBS WHERE JOB_ID = 1)
        INSERT INTO JOBS VALUES (1, 'Software Engineer', 40000.00, 80000.00);

    IF NOT EXISTS (SELECT * FROM JOBS WHERE JOB_ID = 2)
        INSERT INTO JOBS VALUES (2, 'Data Analyst', 35000.00, 70000.00);

    IF NOT EXISTS (SELECT * FROM EMPLOYEES WHERE EMPLOYEE_ID = 1)
        INSERT INTO EMPLOYEES VALUES (1, 'John', 'Doe', 'jon.doe@example.com', '1234567890', '2024-01-15', 1, 60000.00, NULL, NULL, 10);

    IF NOT EXISTS (SELECT * FROM EMPLOYEES WHERE EMPLOYEE_ID = 2)
        INSERT INTO EMPLOYEES VALUES (2, 'Jane', 'Smith', 'jne.smith@example.com', '0987654321', '2024-02-20', 2, 55000.00, NULL, NULL, 11);

    IF NOT EXISTS (SELECT * FROM EMPLOYEES WHERE EMPLOYEE_ID = 3)
        INSERT INTO EMPLOYEES VALUES (3, 'Alice', 'Johnson', 'alic.johnson@example.com', '1231231234', '2024-03-01', 1, 65000.00, NULL, NULL, 11);


    IF NOT EXISTS (SELECT * FROM JOB_HISTORY WHERE EMPLOYEE_ID = 1 AND STARTING_DATE = '2024-01-15')
        INSERT INTO JOB_HISTORY VALUES (1, '2024-01-15', '2024-04-15', 4, 10);

    IF NOT EXISTS (SELECT * FROM JOB_HISTORY WHERE EMPLOYEE_ID = 2 AND STARTING_DATE = '2024-02-20')
        INSERT INTO JOB_HISTORY VALUES (2, '2024-02-20', '2024-05-20', 5, 11);
END
GO

EXEC [dbo].[InsertData];

  SELECT * FROM JOBS



IF EXISTS(SELECT* FROM sys.objects WHERE object_id=OBJECT_ID(N'[dbo].[GetTotalDepartmentSalary]') AND type in (N'FN', N'IF', N'TF', N'FS', N'FT'))
DROP FUNCTION [dbo].[GetTotalDepartmentSalary]
GO

CREATE FUNCTION [dbo].[GetTotalDepartmentSalary] (@DeptName VARCHAR(100))
RETURNS NUMERIC(10,2)
AS
BEGIN
  DECLARE @TotalSalary NUMERIC(10,2)

  SELECT @TotalSalary=SUM(e.SALARY)
  FROM EMPLOYEES e
  JOIN DEPARTMENTS d ON e.DEPARTMENT_ID=d.DEPARTMENT_ID
  WHERE d.DEPARTMENT_NAME=@DeptName

  RETURN ISNULL(@TotalSalary,0)
  END
  GO

SELECT e.FIRST_NAME + ' ' + e.LAST_NAME AS FULL_NAME,l.STREET_ADDRESS,l.POSTAL_CODE,c.COUNTRY_NAME
 FROM EMPLOYEES e
 JOIN DEPARTMENTS d ON  d.DEPARTMENT_ID=e.DEPARTMENT_ID
 JOIN LOCATIONS l ON l.LOCATION_ID=d.DEPARTMENT_ID
 JOIN COUNTRIES c ON l.COUNTRY_ID=c.COUNTRY_ID

SELECT dbo.GetTotalDepartmentSalary('IT') TotalSalary;


SELECT*
FROM EMPLOYEES e
WHERE e.Salary > ( SELECT AVG(SALARY) FROM EMPLOYEES WHERE DEPARTMENT_ID=(SELECT DEPARTMENT_ID FROM DEPARTMENTS WHERE DEPARTMENT_NAME='Marketing'));
 
 
SELECT e.FIRST_NAME + ' ' + e.LAST_NAME AS FULL_NAME,d.DEPARTMENT_NAME,l.STREET_ADDRESS, l.POSTAL_CODE, c.COUNTRY_NAME
FROM  EMPLOYEES e
JOIN  DEPARTMENTS d ON e.DEPARTMENT_ID = d.DEPARTMENT_ID
JOIN LOCATIONS l ON d.LOCATION_ID = l.LOCATION_ID
JOIN  COUNTRIES c ON l.COUNTRY_ID = c.COUNTRY_ID;


SELECT d.DEPARTMENT_ID,COUNT(e.EMPLOYEE_ID) AS EmployeeCount,SUM(e.SALARY) AS TotalSalary
FROM DEPARTMENTS d
JOIN EMPLOYEES e ON d.DEPARTMENT_ID=e.DEPARTMENT_ID
GROUP BY
d.DEPARTMENT_ID
HAVING 
COUNT(e.EMPLOYEE_ID)>5;

select*
from personal

select*
from DPLANPERIOD
WHERE ID>=705 AND ID<=720


SELECT*
from DPLANABR

DECLARE @MinSalaryIncreasing DECIMAL(5,2)=0.20;
--MERGE TASK
MERGE JOBS AS t
USING (
SELECT DISTINCT j.JOB_ID,
			    J.MIN_SALARY*(1+@MinSalaryIncreasing) AS NewMinSalary
  FROM JOBS j
  JOIN JOB_HISTORY jh ON j.JOB_ID=jh.JOB_ID
  )AS s
  ON t.JOB_ID=s.JOB_ID
  WHEN MATCHED THEN UPDATE SET t.MIN_SALARY=s.NewMinSalary;


 --cursor task

  DECLARE  @Employee_ID INT ,
	 @First_Name VARCHAR(50), 
	 @Last_Name VARCHAR(50),
	 @Email VARCHAR(100)  ,
	 @Phone_Number VARCHAR(10),
	 @Hire_Date DATE,
	 @Job_ID INT ,
	 @Salary DECIMAL(10,2),
	 @Comission_Pct DECIMAL(10,2),
	 @Manager_ID INT,
	 @Department_ID INT;


CREATE TABLE #SortedEmployees(
     Employee_ID INT ,
	 First_Name VARCHAR(50) NOT NULL,
	 Last_Name VARCHAR(50) NOT NULL,
	 Email VARCHAR(100)  NOT NULL,
	 Phone_Number VARCHAR(10),
	 Masked_Number VARCHAR(10),
	 Hire_Date DATE NOT NULL,
	 Job_ID INT NOT NULL,
	 Salary DECIMAL(10,2) NOT NULL,
	 Comission_Pct DECIMAL(10,2),
	 Manager_ID INT,
	 Department_ID INT
);

DECLARE employee_cursor CURSOR FOR
SELECT*
from employees
order by salary desc;

open employee_cursor;
FETCH NEXT FROM employee_cursor INTO @Employee_ID, @First_Name,@Last_Name,@Email,@Phone_Number,@Hire_Date, @Job_ID,@Salary,@Comission_Pct,@Manager_ID, @Department_ID;

WHILE @@FETCH_STATUS=0
BEGIN
    DECLARE @MaskedNumber VARCHAR(10)=LEFT(@Phone_Number,LEN(@Phone_Number)-3)+ '***';

	INSERT INTO #SortedEmployees( Employee_ID,First_Name,Last_Name,Email,Phone_Number,Masked_Number,Hire_Date,Job_ID ,Salary,Comission_Pct,Manager_ID,Department_ID)
	VALUES(@Employee_ID,@First_Name,@Last_Name, @Email,@Phone_Number, @MaskedNumber, @Hire_Date, @Job_ID,@Salary,@Comission_Pct,@Manager_ID,@Department_ID);
	  
	FETCH NEXT FROM employee_cursor INTO @Employee_ID,@First_Name,@Last_Name, @Email,@Phone_Number, @Hire_Date, @Job_ID,@Salary,@Comission_Pct,@Manager_ID,@Department_ID;
END

CLOSE employee_cursor;
DEALLOCATE employee_cursor;

SELECT* FROM #SortedEmployees;

DROP TABLE #SortedEmployees;




--dynamic and with task

;WITH AvgSalary  AS(
 SELECT AVG(SALARY) AS AvgDeptSalary
 FROM EMPLOYEES e
 WHERE e.DEPARTMENT_ID= (SELECT DEPARTMENT_ID FROM DEPARTMENTS WHERE DEPARTMENT_NAME='Marketing'))


 SELECT e.Employee_ID, e.FIRST_NAME,e.LAST_NAME,e.SALARY,e.DEPARTMENT_ID
 FROM EMPLOYEES e
 WHERE e.SALARY >(SELECT AvgDeptSalary FROM AvgSalary)


DECLARE @DepartmentName VARCHAR(100)='Marketing';
DECLARE @SQL VARCHAR(MAX)

SET @SQL=';WITH AvgSalary  AS(
 SELECT AVG(SALARY) AS AvgDeptSalary
 FROM EMPLOYEES e
 WHERE e.DEPARTMENT_ID= (SELECT DEPARTMENT_ID FROM DEPARTMENTS WHERE DEPARTMENT_NAME='''+ @DepartmentName +''' ))


  SELECT e.Employee_ID, e.FIRST_NAME,e.LAST_NAME,e.SALARY,e.DEPARTMENT_ID
 FROM EMPLOYEES e
 WHERE e.SALARY >(SELECT AvgDeptSalary FROM AvgSalary)'

EXEC (@SQL);

--task select with pivot

SELECT*
INTO #TempAvgSalary
FROM(
   SELECT DEPARTMENT_NAME, AVG(SALARY) AS AvgSalary
   FROM DEPARTMENTS d
   LEFT JOIN EMPLOYEES e ON e.DEPARTMENT_ID=d.DEPARTMENT_ID
   GROUP BY DEPARTMENT_NAME
   ) A
   PIVOT (
   MAX(AvgSalary)
   FOR DEPARTMENT_NAME IN ([Marketing],[IT])
   )AS PivotTable;

    SELECT* FROM #TempAvgSalary

	DROP TABLE #TempAvgSalary

